---
  - name: Install and configure Datadog Agent for Apache monitoring
    hosts: "{{ vm_name }}"
    become: true
    vars:
      datadog_api_key: "{{ datadog_api_key }}"
      datadog_site: "us5.datadoghq.com"  # Change if using Datadog EU or another site
      apache_service: "httpd"  # Change if using a different Apache service name

    tasks:  
      # - name: Run Agent Install Script
      #   ansible.builtin.shell: |
      #     DD_API_KEY={{ datadog_api_key }} DD_SITE={{ datadog_site }} bash -c "$(curl -L https://install.datadoghq.com/scripts/install_script_agent7.sh)"
      #   args:
      #     executable: /bin/bash
      - name: Install Apache if not already installed
        ansible.builtin.dnf:
          name: httpd
          state: present
          update_cache: yes
          
      - name: Install mod_status for Apache
        lineinfile:
          path: /etc/httpd/conf/httpd.conf
          insertafter: '^#LoadModule status_module'
          line: 'LoadModule status_module modules/mod_status.so'
          state: present
        notify: restart apache
  
      - name: Enable ExtendedStatus in Apache configuration
        lineinfile:
          path: /etc/httpd/conf/httpd.conf
          insertafter: '^#ExtendedStatus'
          line: 'ExtendedStatus On'
          state: present
        notify: restart apache
  
      - name: Configure Apache to allow access to server-status page
        blockinfile:
          path: /etc/httpd/conf.d/status.conf
          create: yes
          block: |
            <Location /server-status>
                SetHandler server-status
                Require local
            </Location>
        notify: restart apache

      - name: Enable and start the Datadog Agent service
        ansible.builtin.service:
          name: datadog-agent.service
          state: started
          enabled: true

      - name: Configure Apache integration for Datadog in conf.yaml
        ansible.builtin.copy:
          dest: /etc/datadog-agent/conf.d/apache.d/conf.yml
          content: |
            init_config:
            instances:
              ## @param apache_status_url - string - required
              ## Status url of your Apache server.
              #
              - apache_status_url: http://localhost/server-status?auto
              
      - name: Restart Datadog agent on RHEL
        ansible.builtin.service:
            name: datadog-agent
            state: restarted
            enabled: true

    handlers:
     - name: restart apache
       ansible.builtin.service:
         name: httpd
         state: restarted

  
